# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9c3f166cdf469704aac39329a7d6661ac85684565581f7e99256ff0b8581b66bcf8e647b1aa355f7f0e24bb140f49d9022ad278bc46146261d52bdfbc65bc9d

test:
  secret_key_base: 530f6dbb58855ffb48b44511b3d5583b8923657bab59e064f3a3797a919b5a2409b6ff943e52c56c46f011b908315db944427d4840509ae6b313be7fad075f2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
